--- 
before_script: 
  - "export PATH=\"$PATH:$HOME/.cargo/bin\""
  - "which rustfmt || cargo install rustfmt"
cache: cargo
language: rust
script: 
  - "cargo fmt -- --write-mode=diff"
  - "cargo build"
  - "cargo test"
